# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='first_app.User')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='first_app.Wish')),
            ],
        ),
    ]
